start = xml
xml = element xml {source, poem}
source = element source {title, author, date}
title = element title {attribute level {"book" | "magazine" | "newspaper"}, "Montage of a Dream Deferred"}
author = element author {"Langston Hughes"}
datePattern = (xsd:date | xsd:gYearMonth| xsd:gYear)
date = element date {when}
when = attribute when {datePattern}
poem = element poem {element title {attribute level {"inner"}, text}, lg+}
lg = element lg {ln+}
ln = element ln {n, mixed{(placeName | place | motif)*}}
n = attribute n {xsd:int}
placeName = element placeName {attribute ref {("NYC-Harlem" | "NYC-Man")?}, text}
place = element place {attribute ref {("NYC-Harlem" | "NYC-PennSt" | "NYC-Brook" | "NYC-Bronx" | "NYC-Man" | "PR" | "Cuba" | "NYC" | "Ga" | "Fla" | "La" | "Ha" | "Ja" )?}, text}
motif = element motif {"a dream deferred"}