start = letter
letter = element letter {n, sender, date, source, message}
n |= attribute n {xsd:int}
sender = attribute sender {"Marian Baldwin"}
datePattern = (xsd:date | xsd:gYearMonth | xsd:gYear)
date |= attribute date {datePattern}
source = attribute source {text}
message = element message {line+, p+}
line = element line {n, date?, text}
n |= attribute n {xsd:int}
date |= element date {text}
p = element p {n, (location | warAid | emote | person | time | ethnicity | character | text)*}
n |= attribute n {xsd:int}
location = element location {(city | country | continent | state | island | sea)*, text}
city = attribute city {"Paris" | "New York"}
country = attribute country {"France" | "Haiti"}
continent = attribute continent {"Europe" | "United States"}
state = attribute state {"New York"}
island = attribute island {"Hispaniola"}
sea = attribute sea {"Caribbean Sea"}
warAid = element warAid {organization?, text}
organization = attribute organization {"American Fund for French Wounded"}
emote = element emote {text}
person = element person {name?, job?, text}
name = attribute name {"Frank Sayre"}
job = attribute job {"sailor"}
time = element time {text}
ethnicity = element ethnicity {origin, text}
origin |= attribute origin {"Italy" | "France"}
character = element character {origin, text}
origin |= attribute origin {text}
