start = doc 
doc = element doc {siteHead, info, instruct, ingList, metadata, notes, metadata}
siteHead = element siteHead {text}
info = element info {dish, taste, timeDuration}
dish |= element dish {"Rocchetti pasta with Brussels sprouts, tomato, eggplant, and paprika"}
taste = element taste {text}
timeDuration |= element timeDuration {(time | timeSpan)+, unit?, text}
time |= attribute time {xsd:int}
timeSpan = attribute timeSpan {text}
unit |= attribute unit {("min" | "ounces" | "pound" | "large" | "medium" | "tablespoon" | "teaspoon" | "pinch")?}
instruct = element instruct {title, step+}
title |= element title {("Instructions" | "Ingredients" | "Recipe notes")?}
step = element step {n, mixed{(ing | temp | timeDuration)*}}
n |= attribute n {xsd:int}
ing |= element ing {type, text}
quant = element quant {unit, (xsd:float | ("Pinch" | "pinch"))?}
type = attribute type {("seasoning" | "vegetable" | "fruit" | "starch" | "dairy" | "herb" | "liquid" | "vegan alt")?}
temp = element temp {fahrenheit?, celsius?, text}
fahrenheit  = attribute fahrenheit {xsd:int}
celsius = attribute celsius {xsd:int}
ingList = element ingList {title, servings, element ing {type, quant?, text}+}
servings = element servings {serves, text}
serves = attribute serves {xsd:int}
metadata = element metadata {mixed{(datePublished | dateAccessed | dish | site | url | pageNum)*}}
datePattern = (xsd:date | xsd:gYearMonth| xsd:gYear)
datePublished = element datePublished {when, text}
dateAccessed = element dateAccessed {when, text}
when |= attribute when {datePattern}
site = element site {"OpenStove"}
url = element url {"https://openstove.org/recipes/rocchetti-pasta" | "openstove.org/recipes/rocchetti-pasta"}
pageNum = element pageNum {"1/2" | "2/2"}
notes = element notes {mixed{title, note+}}
note = element note {n, mixed{ing+}}
